### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by baw** [baw/scala-worksheet-plus#1]
[Enter steps to reproduce below:]
1. Run command

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [scala-worksheet-plus](https://github.com/imamathwiz/scala-worksheet-plus) package, v0.3.12
### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1119

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1119:26)
  at Object.exports.spawn (child_process.js:977:9)
  at ScalaProcess.module.exports.ScalaProcess.initialize (/Users/brian/.atom/packages/scala-worksheet-plus/lib/scala-process.coffee:15:27)
  at Object.module.exports.prepareRun (/Users/brian/.atom/packages/scala-worksheet-plus/lib/scala-worksheet.coffee:30:21)
  at atom-workspace.<anonymous> (/Users/brian/.atom/packages/scala-worksheet-plus/lib/scala-worksheet.coffee:12:8)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -2:29.1.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:32 core:close (atom-text-editor.editor.is-focused)
     -0:59.1.0 application:new-window (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:53.5.0 advanced-new-file:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:45.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25 core:save (atom-text-editor.editor.is-focused)
  2x -0:21 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:19.9.0 editor:select-to-end-of-word (atom-text-editor.editor.mini.is-focused)
     -0:19.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:19.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.8.0 scala-worksheet:run (atom-text-editor.editor.is-focused)
```

**Comment by baw** [comment]
fixed
