### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by zavalit** [baw/scala-worksheet-plus#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [scala-worksheet-plus](https://github.com/imamathwiz/scala-worksheet-plus) package 0.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/zavalit/.atom/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:43

TypeError: Cannot read property 'replace' of undefined
    at ScalaLineProcessor.module.exports.ScalaLineProcessor.formatLine (/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:43:16)
    at ScalaLineProcessor.module.exports.ScalaLineProcessor.processLine (/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:35:21)
    at ScalaProcess.blockCallback (/packages/scala-worksheet-plus/lib/scala-worksheet.coffee:30:23)
    at ScalaProcess.module.exports.ScalaProcess.processResultBlock (/packages/scala-worksheet-plus/lib/scala-process.coffee:39:8)
    at ScalaProcess.module.exports.ScalaProcess.processOut (/packages/scala-worksheet-plus/lib/scala-process.coffee:49:8)
    at /packages/scala-worksheet-plus/lib/scala-process.coffee:16:41)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -1:38.4.0 core:copy (div.package-readme.native-key-bindings)
     -1:07.0 core:backspace (input.hidden-input)
     -1:00.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  7x -0:54.1.0 core:backspace (input.hidden-input)
     -0:52.5.0 editor:consolidate-selections (input.hidden-input)
     -0:52.5.0 core:cancel (input.hidden-input)
     -0:50.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:49.6.0 editor:consolidate-selections (input.hidden-input)
     -0:49.6.0 core:cancel (input.hidden-input)
     -0:47.9.0 core:backspace (input.hidden-input)
     -0:45.9.0 command-palette:toggle (input.hidden-input)
  2x -0:40.8.0 core:move-down (input.hidden-input)
     -0:38.8.0 core:confirm (input.hidden-input)
     -0:38.8.0 scala-worksheet-plus:run (input.hidden-input)
     -0:35.5.0 core:move-down (input.hidden-input)
  2x -0:35.1.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
language-scala 1.1.8 
scala-worksheet-plus 0.4.2 
```

**Comment by baw** [comment]
fixed with 0.5.0 release

Thanks for reporting
