### ISSUE TITLE
Cannot open worksheet: Uncaught TypeError: Cannot read property 'moveToTop' of undefined

### ISSUE THREAD

**Issue by raboof** [baw/scala-worksheet-plus#3]
```
/home/aengelen/.atom/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:4
Hide Stack Trace
TypeError: Cannot read property 'moveToTop' of undefined
  at new ScalaLineProcessor (/home/aengelen/.atom/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:4:18)
  at Object.module.exports.prepareRun (/home/aengelen/.atom/packages/scala-worksheet-plus/lib/scala-worksheet.coffee:25:23)
  at atom-workspace.atom.commands.add.scala-worksheet-plus:run (/home/aengelen/.atom/packages/scala-worksheet-plus/lib/scala-worksheet.coffee:15:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)
```

**Comment by raboof** [comment]
Ah, this is when starting the worksheet when on the 'preferences' tab. I did not realize I have to open a scala file myself and then start the worksheet.
