### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by kid7st** [baw/scala-worksheet-plus#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [scala-worksheet-plus](https://github.com/imamathwiz/scala-worksheet-plus) package, v0.4.2
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/Kid7st/.atom/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:43

TypeError: Cannot read property 'replace' of undefined
    at ScalaLineProcessor.module.exports.ScalaLineProcessor.formatLine (/Users/Kid7st/.atom/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:43:16)
    at ScalaLineProcessor.module.exports.ScalaLineProcessor.processLine (/Users/Kid7st/.atom/packages/scala-worksheet-plus/lib/scala-line-processor.coffee:35:21)
    at ScalaProcess.blockCallback (/Users/Kid7st/.atom/packages/scala-worksheet-plus/lib/scala-worksheet.coffee:30:23)
    at ScalaProcess.module.exports.ScalaProcess.processResultBlock (/Users/Kid7st/.atom/packages/scala-worksheet-plus/lib/scala-process.coffee:39:8)
    at ScalaProcess.module.exports.ScalaProcess.processOut (/Users/Kid7st/.atom/packages/scala-worksheet-plus/lib/scala-process.coffee:49:8)
    at Socket.<anonymous> (/Users/Kid7st/.atom/packages/scala-worksheet-plus/lib/scala-process.coffee:16:41)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
### Commands

```
     -0:36.6.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:36 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:35.4.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:33.2.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode.hyperclick)
     -0:29.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.6.0 scala-worksheet-plus:run (atom-text-editor.editor.vim-mode.normal-mode.hyperclick)
  5x -0:28.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:25.5.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:22.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.7.0 ensime:start (atom-text-editor.editor.vim-mode.normal-mode)
     -0:10.8.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused.hyperclick)
     -0:10 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:09.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:06.9.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 scala-worksheet-plus:run (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "atom-csv-markdown",
      "emmet"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "scala-worksheet-plus": {
    "scalaProcess": "/usr/local/bin/scala"
  }
}
```
### Installed Packages

``` coffee
# User
Ensime, v0.38.1
atom-ternjs, v0.13.2
autocomplete-clang, v0.8.9
autocomplete-json, v1.9.1
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
browser-plus, v0.0.54
emmet, v2.4.3
express-complete, v0.2.0
file-icons, v1.6.19
hyperclick, v0.0.35
intentions, v1.0.5
language-cpp14, v0.6.0
language-latex, v0.6.1
language-scala, v1.1.6
language-scala-plus, v1.2.2
linter, v1.11.4
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-pigments, v0.2.0
minimap-selection, v4.4.0
pretty-json, v0.4.1
project-view, v0.5.0
scala-worksheet-plus, v0.4.2
seti-syntax, v0.4.2
seti-ui, v0.9.2
sync-settings, v0.7.2
vim-mode, v0.65.0
vim-mode-visual-block, v0.2.15
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by baw** [comment]
fixed with 0.5.0 release

Thanks for reporting
